apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: backend
  name: backend
spec:
  serviceName: "backend"
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
      - name: todo-storage
        persistentVolumeClaim:
          claimName: todo-pvc
      containers:
      - image: mariadb:latest
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: MYSQL_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: todo-configmap
              key: MYSQL_DB
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: todo-storage
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"